# tasks file
---
- import_tasks: version-support.yml
  tags:
    - configuration
    - percona-server
    - percona-server-version-support

- import_tasks: first-run.yml
  tags:
    - configuration
    - percona-server
    - percona-server-first-run

- import_tasks: repository.yml
  tags:
    - configuration
    - percona-server
    - percona-server-repository

- import_tasks: install.yml
  tags:
    - configuration
    - percona-server
    - percona-server-install

- import_tasks: configure.yml
  tags:
    - configuration
    - percona-server
    - percona-server-configure

- import_tasks: toolkit-udfs.yml
  tags:
    - configuration
    - percona-server
    - percona-server-toolkit-udfs
  when: percona_server_toolkit_udfs_manage | bool

- import_tasks: zoneinfo.yml
  tags:
    - configuration
    - percona-server
    - percona-server-zoneinfo
  when: percona_server_zoneinfo_manage | bool

- import_tasks: databases.yml
  tags:
    - configuration
    - percona-server
    - percona-server-databases

- import_tasks: users.yml
  tags:
    - configuration
    - percona-server
    - percona-server-users

- import_tasks: plugins.yml
  tags:
    - configuration
    - percona-server
    - percona-server-plugins

- import_tasks: queries.yml
  tags:
    - configuration
    - percona-server
    - percona-server-queries

- import_tasks: ib-logfile.yml
  tags:
    - configuration
    - percona-server
    - percona-server-ib-logfile

- name: start and enable service
  service:
    name: mysql
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - percona-server-start-enable-service
